services:
  vote:
    build: ./vote
    ports:
      - "8080:8080"
    restart: always
    networks:
      - frontend
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
  
  worker:
    build: ./worker
    restart: always
    networks:
      - backend
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.2.3-alpine
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16.0-alpine
    networks:
      - frontend
      - backend
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  redisdata:
  postgresdata:
networks:
  frontend:
  backend:

